source 'https://rubygems.org'
# source 'https://ruby.taobao.org'

# Middleman Gems
gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'
gem 'middleman-blog'
gem 'middleman-deploy', '2.0.0.pre.alpha'
gem 'redcarpet'
gem "middleman-syntax"
