// 定义了全部的 action type
export const INIT_APP = 'INIT_APP';
// comment
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const CREATE_COMMENTS = 'CREATE_COMMENTS';
export const CREATE_COMMENTS_SUCCESS = 'CREATE_COMMENTS_SUCCESS';
export const CREATE_COMMENTS_FAILURE = 'CREATE_COMMENTS_FAILURE';

// auth
export const FETCH_AUTH = 'FETCH_AUTH';
export const JUMP_TO_AUTH_PAGE = 'JUMP_TO_AUTH_PAGE';
export const USER_LOGINED = 'USER_LOGINED';
export const USER_UNLOGINED = 'USER_UNLOGINED';
